### ISSUE TITLE
Comment Styling and Copy Pasting

### ISSUE THREAD

**Issue by FerociousTruth** [Discordius/Lesswrong2#266]
So the comment box says it supports markdown, and no editor appears when editing a comment.  However, markdown doesn't seem to work #264, and when you paste in text, it can pick up strange styling that is then included in the comment you are submitting.  For example, on a [draft post of mine](https://www.lesserwrong.com/posts/xhtFjkwvyBsCM8uRM/change-from-link-post/), I first made a comment "Copy Me" and submitted it.  Then I wrote a new comment with some text and then copied the text from the previous comment into the new comment.  The copied text is bold.

![image](https://user-images.githubusercontent.com/19802624/32379981-55da02f8-c085-11e7-8a4c-2ad0b7a6dda8.png)

**Comment by Discordius** [comment]
Yeah, I also noticed that all copy-pasted content is bold, which is weird. 

We should probably generally override the default draft-js paste-handler and make it so that you can paste any HTML that we export into the editor without it breaking (which should be doable on the client). If anything but me wants to tackle this, here is the relevant documentation: https://draftjs.org/docs/api-reference-editor.html
