### ISSUE TITLE
Deleting image then adding a new one leaves original image

### ISSUE THREAD

**Issue by zejacobi** [Discordius/Lesswrong2#323]
Screenshots are for [this post](https://www.lesserwrong.com/posts/ijwJnK9fCKqQWRhLL/my-predictions-for-2018-and-a-template-for-yours). Note the broken image icon (the old image) and the not broken one (the new image) co-existing, despite only one being visible in the editor.

This is maybe caused by the broken image being invisible (and therefore very hard to delete) in the editor, but I wasn't able to find an img tag in the editor for the old image, so I don't think that's the case. 

How things seem live
<img width="744" alt="screen shot 2018-01-02 at 11 07 29 pm" src="https://user-images.githubusercontent.com/8496595/34508833-f4a97704-f011-11e7-8ade-de0523ea619c.png">

How things seem in the editor
<img width="733" alt="screen shot 2018-01-02 at 11 07 12 pm" src="https://user-images.githubusercontent.com/8496595/34508834-f4b40854-f011-11e7-953a-ea2948e88b5a.png">

**Comment by Discordius** [comment]
So this was a really weird situation, where for some reason the image was part of the last paragraph before the image. 

I successfully fixed it by just deleted that paragraph and retyping it, but it would be great to avoid this in generality. But it might just never come up again, since it was a weird markup situation. Will close this until we see this happening another time.
